### ISSUE TITLE
How do I have different live search settings for different search forms?

### ISSUE THREAD

**Issue by charlesdeb** [msaari/relevanssi-live-ajax-search#11]
I have somewhat figured out how to set the live search up for different forms using the `relevanssi_live_search_get_search_form_config` filter and then the `data-rlvconfig="my-config"` setting on each search form.

Other configuration appears to be set with other filters, like `relevanssi_live_search_status_location`. However, it appears that these filters are all added during the `init` phase, when the plugin is initiated. I'd like to be able to add a filter when a specific template loads - so that I can make some template/page specific changes. 

For example, I want to use different results templates in different places.

Putting this code:

```
add_filter('relevanssi_live_search_results_template', function ($template) {

    global $wp_query;
    error_log($wp_query->post->post_name);

    $slug = get_post_field('post_name', get_post());
    error_log($slug);

    error_log('in relevanssi_live_search_results_template');
    error_log($template);

    return $template;
});
```
in the page template just doesn't work. The filter never gets applied, and nothing ever gets sent to the error log. That wasn't a huge surprise to me.

Putting the exact same code in `functions.php` (which is a much more standard way of doing things of course) does result in this code being called, but (probably) due to the way Relevanssi monkeys with WP's inner workings, both `get_post_field('post_name', get_post())` and `$wp_query->post->post_name` refer to the first post in the search results, and _not_ the current page I am on. If I knew the current page, then I could programmatically change `$template` and use the correct search results template file.

I'm guessing there is a simple solution to this and that I can't be the only person to want to have more than one search results template. Can you point me in the right direction here? We are prepared to purchase the pro version of relevanssi if it makes a difference.

BTW, you have some documentation and a few examples in the normal relevanssi page for how to use the different filters, but other than the list of hooks [here](https://www.relevanssi.com/live-ajax-search/) with a little bit of explanation, I can't see anything else explained. Some examples would go a long way for helping people get up to speed with this.

**Comment by msaari** [comment]
Documenting the Live Ajax Search is indeed a work-in-progress. Part of that is because the default use case (and the way I pretty much use it myself) is to just plug and play, without any changes to the settings. I'm sure I'll eventually get to expanding the filter documentation, but there's also much less pressure to document unusual use cases as I don't know of them. Questions like yours are very rare with this plugin; with Relevanssi, I have tons of questions and user problems to work from. From my perspective, you are, so far, the only person to want to have more than one search results template ;-)

Anyway, the main reason your function does not work is that it is being run in the AJAX context. Even if you did your function before Relevanssi messes up with the `$wp_query`, the `$wp_query` would still be empty. This all happens inside an AJAX request that simply does not have any information about the page that made the query.

In order to have that information, you need to pass that information. The only way to do that is to include it in the request. This would be a simple method of doing that:
```
add_filter( 'get_search_form', function( $form ) {
    return str_replace( '</form>', '<input type="hidden" name="source" value="' . get_post_field('post_name', get_post() ) . '"></form>', $form );
} );
```

This would include the post slug in a "source" request parameter. Then you can just read it from the `$_REQUEST` global and adjust the template as necessary:

```
add_filter( 'relevanssi_live_search_results_template', function( $template ) {
    $slug = $_REQUEST['source'];
    return $template;
} );
```

**Comment by charlesdeb** [comment]
Thanks for the speedy reply.

D'oh moment - of course it doesn't know the template because it's an ajax call. I've been caught on that before! Thanks.

I have implemented your suggestion, although instead of using the `get_search_form` filter, I have just hard-coded that hidden field into each of my search forms - just to make it slightly easier for future developers to see what is going on. Many thanks.

**Comment by msaari** [comment]
I too had to spend a good moment thinking about this before I figured it out...
